flatpak install flathub com.axosoft.GitKraken -y
flatpak install flathub com.bitwarden.desktop -y
flatpak install flathub com.calibre_ebook.calibre -y
flatpak install flathub com.felipekinoshita.Wildcard -y
flatpak install flathub com.getpostman.Postman -y
flatpak install flathub com.github.johnfactotum.Foliate -y
flatpak install flathub com.github.marhkb.Pods -y
flatpak install flathub com.github.muriloventuroso.easyssh -y
flatpak install flathub com.github.tchx84.Flatseal -y
flatpak install flathub com.github.xournalpp.xournalpp -y
flatpak install flathub com.google.Chrome -y
flatpak install flathub com.jgraph.drawio.desktop -y
flatpak install flathub com.microsoft.Edge -y
flatpak install flathub com.obsproject.Studio -y
flatpak install flathub com.ticktick.TickTick -y
flatpak install flathub com.wps.Office -y
flatpak install flathub io.dbeaver.DBeaverCommunity -y
flatpak install flathub io.github.giantpinkrobots.flatsweep -y
flatpak install flathub io.github.peazip.PeaZip -y
flatpak install flathub io.github.realmazharhussain.GdmSettings -y
flatpak install flathub io.github.shiftey.Desktop -y
flatpak install flathub io.github.spacingbat3.webcord -y
flatpak install flathub io.github.webcamoid.Webcamoid -y
flatpak install flathub md.obsidian.Obsidian -y
flatpak install flathub net.nokyan.Resources -y
flatpak install flathub net.sourceforge.projectM -y
flatpak install flathub nl.hjdskes.gcolor3 -y
flatpak install flathub org.audacityteam.Audacity -y
flatpak install flathub org.chromium.Chromium -y
flatpak install flathub org.ferdium.Ferdium -y
flatpak install flathub org.filezillaproject.Filezilla -y
flatpak install flathub org.gnome.Boxes -y
flatpak install flathub org.gnome.DejaDup -y
flatpak install flathub org.gnome.EasyTAG -y
flatpak install flathub org.gnome.FontManager -y
flatpak install flathub org.gnome.Lollypop -y
flatpak install flathub org.gnome.clocks -y
flatpak install flathub org.gnome.meld -y
flatpak install flathub org.kde.kid3 -y
flatpak install flathub org.kde.subtitlecomposer -y
flatpak install flathub org.kde.umbrello -y
flatpak install flathub org.musicbrainz.Picard -y
flatpak install flathub org.nicotine_plus.Nicotine -y
flatpak install flathub org.qbittorrent.qBittorrent -y
flatpak install flathub org.remmina.Remmina -y
flatpak install flathub org.strawberrymusicplayer.strawberry -y
flatpak install flathub org.telegram.desktop -y
flatpak install flathub org.texstudio.TeXstudio -y
